# Generated by Django 4.2.6 on 2023-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_diary_end_date_alter_diary_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_name',
            field=models.CharField(max_length=100, verbose_name='Diary'),
        ),
    ]
