# Generated by Django 4.2.6 on 2023-11-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_diary_diary_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='Diary',
        ),
    ]
