# Generated by Django 4.2.6 on 2023-11-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_diary_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='Diary',
        ),
    ]
