# Generated by Django 4.2.6 on 2023-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_diary_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Diary'),
        ),
    ]
