# Generated by Django 4.2.6 on 2023-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_diary_diary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
    ]
